### ISSUE TITLE
Libre menu blank

### ISSUE THREAD

**Issue by tekestmy** [libremfg/getting-started#13]
I am trying to test the standalone version and for some reason I am getting a blank menu. I am not sure what I am missing.
![libre](https://user-images.githubusercontent.com/27015020/159497549-21475e5d-66dd-4929-826c-9fd4fbfc4a37.png)

Do you have any suggestion what I should do to get the main menu to show up?

**Comment by amine-amaach** [comment]
Hi, this is not an issue.
I don't know if you resolve it yet, but after the last update they have tightened up the security on what gets shown in the menu so that it's role based.
To resolve it, you have to access the /users url (localhost/users) and give yourself the admin role.
And it is better to join the discord server to get quick answers.
